# Generated by Django 5.1.3 on 2024-11-22 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('book_title', models.CharField(max_length=250)),
                ('book_name', models.CharField(max_length=250)),
                ('author', models.CharField(max_length=250)),
                ('file', models.FileField(upload_to='books/pdfs')),
                ('image', models.ImageField(upload_to='books/images')),
                ('Category', models.CharField(max_length=250)),
                ('ISBN', models.CharField(max_length=250)),
                ('publication_country', models.CharField(max_length=250)),
                ('Language', models.CharField(max_length=250)),
                ('publication_year', models.CharField(max_length=250)),
            ],
        ),
    ]
